version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 20
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 3.4
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = true
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
naturalist = true
corndelight = true
farmersdelight = true
supplementaries = true
mythicmobs = true
doapi = true
paladins = true
terrestria = true
immersive_portals = true
hamsters = true
brewinandchewin = false
betterend = true
friendsandfoes = true
runes = true
minecraft = true
aquamirae = true
ends_delight = true
nethersdelight = true
betterarcheology = true
amendments = true
adventurez = true
bosses_of_mass_destruction = true
archers = true
handcrafted = true
universal_graves = true
vinery = true
spell_engine = true
expandeddelight = true
blockus = true
azurelib = true
